# https://cs262-monopoly-service.herokuapp.com/

# curl http://localhost:3000/players
GET http://localhost:3000//players

###

# curl
#--header 'Content-Type: application/json'
#--data '{"email":"test@test.com", "name":"test"}'
#http://localhost:3000/players
POST http://localhost:3000/players
Content-Type: application/json

{"email":"test@test.com", "name":"test"}

###

# curl http://localhost:3000/players/4
GET http://localhost:3000/players/4

###

# curl
#-X PUT
#--header 'Content-Type: application/json'
#--data '{"email":"new@test.com", "name": null}'
#http://localhost:3000/player/4
PUT http://localhost:3000/players/4
Content-Type: application/json

{"email": "new@test.com", "name": null}

###

# curl http://localhost:3000/players/4
DELETE http://localhost:3000/players/9

###

